version: "2"

linters:
  default: none
  enable:
    - durationcheck
    - gocritic
    - gomodguard
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    misspell:
      locale: US
    staticcheck:
      checks: ['all', '-SA6002']
  exclusions:
    presets: []
    rules:
      - path: '(.+)\.go$'
        text: should have a package comment
      - path: '(.+)\.go$' 
        text: error strings should not be capitalized or end with punctuation or a newline
      - path: '(.+)\.go$'
        text: should not use ALL_CAPS in Go names; use CamelCase instead
      - path: '(.+)\.go$'
        text: don't use ALL_CAPS in Go names; use CamelCase

formatters:
  enable:
    - gofumpt
    - goimports
